# Generated by Django 2.1.1 on 2018-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_trip',
            old_name='user',
            new_name='created_user',
        ),
        migrations.AddField(
            model_name='my_trip',
            name='trip_user',
            field=models.ManyToManyField(related_name='join_trip', to='login_register.User'),
        ),
    ]
